# Second batch of hand-authored tower monsters - see custom_tower_art.py
# for the full style notes and the grid/palette format, which this file
# reuses verbatim (it imports K/W/P and the render helpers from there).
#
# Where batch one filled the four thinnest cells of the gacha table, this
# batch closes the last five holes in it outright: after batch one the only
# empty type/rarity combinations left were FIRE/LEGENDARY, EARTH/LEGENDARY,
# NORMAL/LEGENDARY, ELECTRIC/EPIC and WATER/EPIC. One line each, so every
# type now has a catchable species at every rarity and no type-restricted
# banner is a near-guaranteed outcome at any tier.
#
# These are meant to sit alongside the Monster Evolution pack rather than
# replace it, so they hold to its conventions - compact silhouette inside a
# clear margin, oversized 2px eyes with the pupil directly beneath, flat
# 2-3 tone fills with the darker shade low, 1px near-black outline - while
# reaching for shapes the pack does not already cover (a drifting jellyfish
# bell, a cracked golem with a lit core, a plumed firebird, a hovering
# temple bell, a caged lightning orb).

from custom_tower_art import K, W, P, PALETTES

PALETTES2 = {
    # WATER/EPIC - jellyfish bell
    'dewdrip': {'K': K, 'W': W, 'P': (35, 145, 185, 255),
                'U': (126, 208, 232, 255), 'V': (58, 132, 186, 255),
                'L': (214, 244, 252, 255), 'T': (92, 176, 212, 255)},
    'tidebell': {'K': K, 'W': W, 'P': (35, 145, 185, 255),
                 'U': (118, 200, 230, 255), 'V': (48, 118, 176, 255),
                 'L': (214, 244, 252, 255), 'T': (84, 168, 208, 255)},
    'maelstrom': {'K': K, 'W': W, 'P': (35, 145, 185, 255),
                  'U': (108, 192, 228, 255), 'V': (36, 100, 162, 255),
                  'L': (226, 250, 255, 255), 'T': (74, 156, 202, 255)},

    # EARTH/LEGENDARY - cracked golem with a lit core
    'pebblet': {'K': K, 'W': W, 'P': (135, 85, 40, 255),
                'S': (150, 140, 126, 255), 'D': (96, 88, 78, 255),
                'C': (250, 186, 84, 255), 'L': (196, 186, 170, 255)},
    'cragfist': {'K': K, 'W': W, 'P': (135, 85, 40, 255),
                 'S': (142, 132, 118, 255), 'D': (88, 80, 70, 255),
                 'C': (252, 178, 66, 255), 'L': (190, 180, 164, 255)},
    'terralith': {'K': K, 'W': W, 'P': (135, 85, 40, 255),
                  'S': (134, 124, 112, 255), 'D': (78, 71, 63, 255),
                  'C': (255, 172, 52, 255), 'L': (186, 176, 160, 255)},

    # FIRE/LEGENDARY - plumed firebird
    'pyrelet': {'K': K, 'W': W, 'P': (230, 70, 30, 255),
                'R': (236, 108, 44, 255), 'M': (166, 52, 30, 255),
                'F': (255, 214, 104, 255), 'O': (255, 158, 58, 255)},
    'blazeplume': {'K': K, 'W': W, 'P': (230, 70, 30, 255),
                   'R': (238, 96, 38, 255), 'M': (152, 44, 26, 255),
                   'F': (255, 222, 122, 255), 'O': (255, 158, 58, 255)},
    'solaris': {'K': K, 'W': W, 'P': (230, 70, 30, 255),
                'R': (242, 88, 34, 255), 'M': (138, 36, 22, 255),
                'F': (255, 236, 150, 255), 'O': (255, 168, 62, 255)},

    # NORMAL/LEGENDARY - hovering temple bell
    'chimeling': {'K': K, 'W': W, 'P': (200, 45, 190, 255),
                  'B': (206, 176, 96, 255), 'D': (138, 110, 52, 255),
                  'L': (244, 226, 162, 255), 'G': (176, 200, 214, 255)},
    'tollward': {'K': K, 'W': W, 'P': (200, 45, 190, 255),
                 'B': (212, 180, 96, 255), 'D': (132, 104, 48, 255),
                 'L': (248, 232, 172, 255), 'G': (168, 194, 210, 255)},
    'carillon': {'K': K, 'W': W, 'P': (200, 45, 190, 255),
                 'B': (222, 190, 100, 255), 'D': (126, 98, 44, 255),
                 'L': (255, 242, 186, 255), 'G': (158, 186, 206, 255)},

    # ELECTRIC/EPIC - caged lightning orb
    'sparkmote': {'K': K, 'W': W, 'P': (50, 55, 150, 255),
                  'A': (128, 204, 240, 255), 'V': (70, 128, 196, 255),
                  'Y': (250, 224, 110, 255), 'L': (226, 246, 255, 255)},
    'arcnode': {'K': K, 'W': W, 'P': (50, 55, 150, 255),
                'A': (118, 198, 240, 255), 'V': (58, 112, 186, 255),
                'Y': (252, 228, 118, 255), 'L': (232, 248, 255, 255)},
    'tesladon': {'K': K, 'W': W, 'P': (50, 55, 150, 255),
                 'A': (108, 190, 238, 255), 'V': (46, 96, 172, 255),
                 'Y': (255, 232, 128, 255), 'L': (238, 250, 255, 255)},
}

# render_monster (custom_tower_art.py) looks palettes up in the module-level
# PALETTES dict by key - merge this batch's in so it resolves both batches
# uniformly regardless of import order.
PALETTES.update(PALETTES2)

CUSTOM_MONSTERS2 = [
    # ---- WATER / EPIC : jellyfish bell ----
    ('dewdrip', 'dewdrip', {
        'down': [
            "......KKKK......",
            ".....KUUUUK.....",
            "....KUULUUUK....",
            "....KUUUUUUK....",
            "....KWWUUWWK....",
            "....KWPUUWPK....",
            "....KUUUUUUK....",
            "....KVUUUUVK....",
            "....KKVVVVKK....",
            ".....KTKKTK.....",
            ".....KTK.KTK....",
            "......K...K.....",
        ],
        'up': [
            "......KKKK......",
            ".....KUUUUK.....",
            "....KUULUUUK....",
            "....KUUUUUUK....",
            "....KUUVVUUK....",
            "....KUVUUVUK....",
            "....KUUUUUUK....",
            "....KVUUUUVK....",
            "....KKVVVVKK....",
            ".....KTKKTK.....",
            ".....KTK.KTK....",
            "......K...K.....",
        ],
        'side': [
            "......KKKK......",
            ".....KUUUUK.....",
            "....KUULUUUK....",
            "....KUUUUUUK....",
            "....KUUUUWWK....",
            "....KUUUUWPKK...",
            "....KUUUUUUKTK..",
            "....KVUUUUVK....",
            "....KKVVVVKK....",
            ".....KTKKTK.....",
            "......KTK.KTK...",
            ".......K...K....",
        ],
    }),
    ('tidebell_mid', 'tidebell', {
        'down': [
            ".....KKKKKK.....",
            "...KKUUUUUUKK...",
            "..KUUULUUUUUK...",
            "..KUUUUUUUUUK...",
            "..KUWWUUUUWWK...",
            "..KUWPUUUUWPK...",
            "..KUUUUUUUUUK...",
            "..KVUUUUUUUVK...",
            "..KVVUUUUUVVK...",
            "..KKVVVVVVVKK...",
            "...KTKTKKTKTK...",
            "...KTK.K.K.KTK..",
            "....K.......K...",
        ],
        'up': [
            ".....KKKKKK.....",
            "...KKUUUUUUKK...",
            "..KUUULUUUUUK...",
            "..KUUUUUUUUUK...",
            "..KUUUVVVUUUK...",
            "..KUUVUUUVUUK...",
            "..KUUUVVVUUUK...",
            "..KVUUUUUUUVK...",
            "..KVVUUUUUVVK...",
            "..KKVVVVVVVKK...",
            "...KTKTKKTKTK...",
            "...KTK.K.K.KTK..",
            "....K.......K...",
        ],
        'side': [
            ".....KKKKKK.....",
            "...KKUUUUUUKK...",
            "..KUUULUUUUUK...",
            "..KUUUUUUUUUK...",
            "..KUUUUUUWWUK...",
            "..KUUUUUUWPUKK..",
            "..KUUUUUUUUUKTK.",
            "..KVUUUUUUUVK...",
            "..KVVUUUUUVVK...",
            "..KKVVVVVVVKK...",
            "...KTKTKKTKTK...",
            "....KTK.K.KTK...",
            ".....K.....K....",
        ],
    }),
    ('maelstrom_evo', 'maelstrom', {
        'down': [
            "..KLK..KLK..KLK.",
            "..KUKKKUUKKKUK..",
            ".KUUUUUUUUUUUK..",
            "KUUULUUUUULUUUK.",
            "KUUUUUUUUUUUUUK.",
            "KUWWUUUUUUUWWUK.",
            "KUWPUUUUUUUWPUK.",
            "KUUUUUUUUUUUUUK.",
            "KVUUUKVVVKUUUVK.",
            "KVVUUUUUUUUUVVK.",
            "KKVVVVVVVVVVVKK.",
            ".KTKTKTKKTKTKTK.",
            ".KTK.K.K.K.K.KTK",
            "..K.........K...",
        ],
        'up': [
            "..KLK..KLK..KLK.",
            "..KUKKKUUKKKUK..",
            ".KUUUUUUUUUUUK..",
            "KUUULUUUUULUUUK.",
            "KUUUUUVVVUUUUUK.",
            "KUUUUVUUUVUUUUK.",
            "KUUUVUUUUUVUUUK.",
            "KUUUUVUUUVUUUUK.",
            "KVUUUUVVVUUUUVK.",
            "KVVUUUUUUUUUVVK.",
            "KKVVVVVVVVVVVKK.",
            ".KTKTKTKKTKTKTK.",
            ".KTK.K.K.K.K.KTK",
            "..K.........K...",
        ],
        'side': [
            "..KLK..KLK..KLK.",
            "..KUKKKUUKKKUK..",
            ".KUUUUUUUUUUUK..",
            "KUUULUUUUUUUUUK.",
            "KUUUUUUUUUUUUUK.",
            "KUUUUUUUUUWWUUK.",
            "KUUUUUUUUUWPUKKK",
            "KUUUUUUUUUUUUKTK",
            "KVUUUKVVVKUUUVK.",
            "KVVUUUUUUUUUVVK.",
            "KKVVVVVVVVVVVKK.",
            ".KTKTKTKKTKTKTK.",
            "..KTK.K.K.K.KTK.",
            "...K.......K....",
        ],
    }),

    # ---- EARTH / LEGENDARY : cracked golem with a lit core ----
    ('pebblet', 'pebblet', {
        'down': [
            "....KKKKKK......",
            "...KSSSSSSK.....",
            "..KSSLSSSSSK....",
            "..KSSSSSSSSK....",
            "..KSWWSSWWSK....",
            "..KSWPSSWPSK....",
            "..KSSSSSSSSK....",
            "..KSSKCCKSSK....",
            "..KDSSCCSSDK....",
            "..KDDSSSSDDK....",
            "...KDDDDDDK.....",
            "...KK....KK.....",
        ],
        'up': [
            "....KKKKKK......",
            "...KSSSSSSK.....",
            "..KSSLSSSSSK....",
            "..KSSSSSSSSK....",
            "..KSSDSSDSSK....",
            "..KSDSSSSDSK....",
            "..KSSSSSSSSK....",
            "..KSSSDDSSSK....",
            "..KDSSSSSSDK....",
            "..KDDSSSSDDK....",
            "...KDDDDDDK.....",
            "...KK....KK.....",
        ],
        'side': [
            "....KKKKKK......",
            "...KSSSSSSK.....",
            "..KSSLSSSSSK....",
            "..KSSSSSSSSK....",
            "..KSSSSSSWWK....",
            "..KSSSSSSWPKK...",
            "..KSSSSSSSSKDK..",
            "..KSSKCCKSSK....",
            "..KDSSCCSSDK....",
            "..KDDSSSSDDK....",
            "...KDDDDDDK.....",
            "...KK....KK.....",
        ],
    }),
    ('cragfist_mid', 'cragfist', {
        'down': [
            "..K..KKKKKK..K..",
            "..KSKSSSSSSKSK..",
            ".KSSSSLSSSSSSSK.",
            ".KSSSSSSSSSSSSK.",
            "KSSSWWSSSSWWSSK.",
            "KSSSWPSSSSWPSSK.",
            "KSSSSSSSSSSSSSK.",
            "KSSSKCCCCKSSSSK.",
            "KSSSKCCCCKSSSSK.",
            "KDSSSSCCSSSSSDK.",
            ".KDDSSSSSSSSDDK.",
            ".KKDDDDDDDDDDKK.",
            "..KK........KK..",
        ],
        'up': [
            "..K..KKKKKK..K..",
            "..KSKSSSSSSKSK..",
            ".KSSSSLSSSSSSSK.",
            ".KSSSSSSSSSSSSK.",
            "KSSSDSSSSSSDSSK.",
            "KSSDSSSSSSSSDSK.",
            "KSSSSSSSSSSSSSK.",
            "KSSSSSDDDSSSSSK.",
            "KSSSSSSSSSSSSSK.",
            "KDSSSSSSSSSSSDK.",
            ".KDDSSSSSSSSDDK.",
            ".KKDDDDDDDDDDKK.",
            "..KK........KK..",
        ],
        'side': [
            "..K..KKKKKK..K..",
            "..KSKSSSSSSKSK..",
            ".KSSSSLSSSSSSSK.",
            ".KSSSSSSSSSSSSK.",
            "KSSSSSSSSSWWSSK.",
            "KSSSSSSSSSWPSKKK",
            "KSSSSSSSSSSSSKDK",
            "KSSSKCCCCKSSSSK.",
            "KSSSKCCCCKSSSSK.",
            "KDSSSSCCSSSSSDK.",
            ".KDDSSSSSSSSDDK.",
            ".KKDDDDDDDDDDKK.",
            "..KK........KK..",
        ],
    }),
    ('terralith_evo', 'terralith', {
        'down': [
            ".K..K.KKKK.K..K.",
            ".KSKSKSSSSKSKSK.",
            "KSSSSSSLSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSWWSSSSSSWWSSK",
            "KSSWPSSSSSSWPSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSKCCCCCCCCKSSK",
            "KSSKCCLCCLCCKSSK",
            "KSSKCCCCCCCCKSSK",
            "KDSSKCCCCCCKSSDK",
            "KDDSSSCCCCSSSDDK",
            ".KDDDSSSSSSDDDK.",
            ".KKDDDDDDDDDDKK.",
            "..KK........KK..",
        ],
        'up': [
            ".K..K.KKKK.K..K.",
            ".KSKSKSSSSKSKSK.",
            "KSSSSSSLSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSDSSSSSSSSDSSK",
            "KSDSSSSSSSSSSDSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSDDDDSSSSSK",
            "KSSSSDSSSSDSSSSK",
            "KSSSSSDDDDSSSSSK",
            "KDSSSSSSSSSSSSDK",
            "KDDSSSSSSSSSSDDK",
            ".KDDDSSSSSSDDDK.",
            ".KKDDDDDDDDDDKK.",
            "..KK........KK..",
        ],
        'side': [
            ".K..K.KKKK.K..K.",
            ".KSKSKSSSSKSKSK.",
            "KSSSSSSLSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSWWSSK",
            "KSSSSSSSSSSWPSKK",
            "KSSSSSSSSSSSSSKD",
            "KSSKCCCCCCCCKSSK",
            "KSSKCCLCCLCCKSSK",
            "KSSKCCCCCCCCKSSK",
            "KDSSKCCCCCCKSSDK",
            "KDDSSSCCCCSSSDDK",
            ".KDDDSSSSSSDDDK.",
            ".KKDDDDDDDDDDKK.",
            "..KK........KK..",
        ],
    }),

    # ---- FIRE / LEGENDARY : plumed firebird ----
    ('pyrelet', 'pyrelet', {
        'down': [
            "......KFK.......",
            ".....KFOFK......",
            "....KKOOOKK.....",
            "...KRRRRRRRK....",
            "..KRRRRRRRRRK...",
            "..KRWWRRRRWWK...",
            "..KRWPRRRRWPK...",
            "..KRRRKOOKRRK...",
            "..KRRRRRRRRRK...",
            "...KMRRRRRRMK...",
            "..KOKMMMMMMKOK..",
            "..KOK.KK.K.KOK..",
            "......K..K......",
        ],
        'up': [
            "......KFK.......",
            ".....KFOFK......",
            "....KKOOOKK.....",
            "...KRRRRRRRK....",
            "..KRRRRRRRRRK...",
            "..KRRMRRRRMRK...",
            "..KRMRRRRRRMK...",
            "..KRRMRRRRMRK...",
            "..KRRRRRRRRRK...",
            "...KMRRRRRRMK...",
            "..KOKMMMMMMKOK..",
            "..KOK.KK.K.KOK..",
            "......K..K......",
        ],
        'side': [
            "......KFK.......",
            ".....KFOFK......",
            "....KKOOOKK.....",
            "...KRRRRRRRK....",
            "..KRRRRRRRRRK...",
            "..KRRRRRRRWWK...",
            "..KRRRRRRRWPKKK.",
            "..KRRRKOOKRRKOOK",
            "..KRRRRRRRRRK...",
            "...KMRRRRRRMK...",
            "..KOKMMMMMMK....",
            "..KOK.KK.K......",
            "......K..K......",
        ],
    }),
    ('blazeplume_mid', 'blazeplume', {
        'down': [
            "..KFK.KFK.KFK...",
            ".KFOFKFOFKFOFK..",
            ".KOOKKOOOKKOOK..",
            "..KKRRRRRRRKK...",
            ".KRRRRRRRRRRRK..",
            ".KRRWWRRRRWWRK..",
            ".KRRWPRRRRWPRK..",
            ".KRRRRKOOKRRRK..",
            ".KRRRRRRRRRRRK..",
            ".KMRRRRRRRRRMK..",
            "KOKMMMMMMMMMMKOK",
            "KOK.KK.KK.KK.KOK",
            ".....K...K......",
        ],
        'up': [
            "..KFK.KFK.KFK...",
            ".KFOFKFOFKFOFK..",
            ".KOOKKOOOKKOOK..",
            "..KKRRRRRRRKK...",
            ".KRRRRRRRRRRRK..",
            ".KRRMRRRRRRMRK..",
            ".KRMRRRRRRRRMK..",
            ".KRRMRRRRRRMRK..",
            ".KRRRRRRRRRRRK..",
            ".KMRRRRRRRRRMK..",
            "KOKMMMMMMMMMMKOK",
            "KOK.KK.KK.KK.KOK",
            ".....K...K......",
        ],
        'side': [
            "..KFK.KFK.KFK...",
            ".KFOFKFOFKFOFK..",
            ".KOOKKOOOKKOOK..",
            "..KKRRRRRRRKK...",
            ".KRRRRRRRRRRRK..",
            ".KRRRRRRRRWWRK..",
            ".KRRRRRRRRWPRKKK",
            ".KRRRRKOOKRRRKOO",
            ".KRRRRRRRRRRRK..",
            ".KMRRRRRRRRRMK..",
            "KOKMMMMMMMMMMK..",
            "KOK.KK.KK.KK....",
            ".....K...K......",
        ],
    }),
    ('solaris_evo', 'solaris', {
        'down': [
            "KFK.KFK.KFK.KFK.",
            "KOFKFOFKFOFKFOK.",
            ".KOOKOOOKOOOKOK.",
            "..KKRRRRRRRRKK..",
            ".KRRRRRRRRRRRRK.",
            "KRRRRRRRRRRRRRRK",
            "KRRWWRRRRRRWWRRK",
            "KRRWPRRRRRRWPRRK",
            "KRRRRKFOOFKRRRRK",
            "KRRRRKOOOOKRRRRK",
            "KRRRRRRRRRRRRRRK",
            "KMRRRRRRRRRRRRMK",
            "KOKMMMMMMMMMMMKO",
            "KOK.KK.KK.KK.KOK",
            "....K...K...K...",
        ],
        'up': [
            "KFK.KFK.KFK.KFK.",
            "KOFKFOFKFOFKFOK.",
            ".KOOKOOOKOOOKOK.",
            "..KKRRRRRRRRKK..",
            ".KRRRRRRRRRRRRK.",
            "KRRRRRRRRRRRRRRK",
            "KRRMRRRRRRRRMRRK",
            "KRMRRRRRRRRRRMRK",
            "KRRMRRRMMRRRMRRK",
            "KRRRMRRRRRRMRRRK",
            "KRRRRRRRRRRRRRRK",
            "KMRRRRRRRRRRRRMK",
            "KOKMMMMMMMMMMMKO",
            "KOK.KK.KK.KK.KOK",
            "....K...K...K...",
        ],
        'side': [
            "KFK.KFK.KFK.KFK.",
            "KOFKFOFKFOFKFOK.",
            ".KOOKOOOKOOOKOK.",
            "..KKRRRRRRRRKK..",
            ".KRRRRRRRRRRRRK.",
            "KRRRRRRRRRRRRRRK",
            "KRRRRRRRRRRWWRRK",
            "KRRRRRRRRRRWPRKK",
            "KRRRRKFOOFKRRRKO",
            "KRRRRKOOOOKRRRRK",
            "KRRRRRRRRRRRRRRK",
            "KMRRRRRRRRRRRRMK",
            "KOKMMMMMMMMMMMK.",
            "KOK.KK.KK.KK....",
            "....K...K...K...",
        ],
    }),

    # ---- NORMAL / LEGENDARY : hovering temple bell ----
    ('chimeling', 'chimeling', {
        'down': [
            ".......KK.......",
            "......KBBK......",
            ".....KKBBKK.....",
            "....KBBBBBBK....",
            "...KBBLBBBBBK...",
            "...KBWWBBWWBK...",
            "...KBWPBBWPBK...",
            "...KBBBBBBBBK...",
            "...KDBBBBBBDK...",
            "..KKDDDDDDDDKK..",
            "..K.KDBBBBDK.K..",
            "......KDDK......",
            ".......KK.......",
            "......KGGK......",
        ],
        'up': [
            ".......KK.......",
            "......KBBK......",
            ".....KKBBKK.....",
            "....KBBBBBBK....",
            "...KBBLBBBBBK...",
            "...KBBDBBDBBK...",
            "...KBDBBBBDBK...",
            "...KBBBBBBBBK...",
            "...KDBBBBBBDK...",
            "..KKDDDDDDDDKK..",
            "..K.KDBBBBDK.K..",
            "......KDDK......",
            ".......KK.......",
            "......KGGK......",
        ],
        'side': [
            ".......KK.......",
            "......KBBK......",
            ".....KKBBKK.....",
            "....KBBBBBBK....",
            "...KBBLBBBBBK...",
            "...KBBBBBBWWK...",
            "...KBBBBBBWPKK..",
            "...KBBBBBBBBKGK.",
            "...KDBBBBBBDK...",
            "..KKDDDDDDDDKK..",
            "..K.KDBBBBDK.K..",
            "......KDDK......",
            ".......KK.......",
            "......KGGK......",
        ],
    }),
    ('tollward_mid', 'tollward', {
        'down': [
            "......KKKK......",
            ".....KBBBBK.....",
            "..KGKKBBBBKKGK..",
            "..KGKBBBBBBKGK..",
            "..KKBBLBBBBBKK..",
            "..KBBWWBBWWBBK..",
            "..KBBWPBBWPBBK..",
            "..KBBBBBBBBBBK..",
            "..KBBBKDDKBBBK..",
            "..KDBBBBBBBBDK..",
            ".KKDDDDDDDDDDKK.",
            ".K.KDBBBBBBDK.K.",
            "....KDDDDDDK....",
            "......KDDK......",
            "......KGGK......",
        ],
        'up': [
            "......KKKK......",
            ".....KBBBBK.....",
            "..KGKKBBBBKKGK..",
            "..KGKBBBBBBKGK..",
            "..KKBBLBBBBBKK..",
            "..KBBBDBBDBBBK..",
            "..KBBDBBBBDBBK..",
            "..KBBBBBBBBBBK..",
            "..KBBBKDDKBBBK..",
            "..KDBBBBBBBBDK..",
            ".KKDDDDDDDDDDKK.",
            ".K.KDBBBBBBDK.K.",
            "....KDDDDDDK....",
            "......KDDK......",
            "......KGGK......",
        ],
        'side': [
            "......KKKK......",
            ".....KBBBBK.....",
            "..KGKKBBBBKKGK..",
            "..KGKBBBBBBKGK..",
            "..KKBBLBBBBBKK..",
            "..KBBBBBBBWWBK..",
            "..KBBBBBBBWPBKK.",
            "..KBBBBBBBBBBKGK",
            "..KBBBKDDKBBBK..",
            "..KDBBBBBBBBDK..",
            ".KKDDDDDDDDDDKK.",
            ".K.KDBBBBBBDK.K.",
            "....KDDDDDDK....",
            "......KDDK......",
            "......KGGK......",
        ],
    }),
    ('carillon_evo', 'carillon', {
        'down': [
            "..KGK.KKKK.KGK..",
            "..KGKKBBBBKKGK..",
            ".KGKBBBBBBBBKGK.",
            ".KGKBBBBBBBBKGK.",
            "KKKBBBLBBBBBBKKK",
            "KBBBWWBBBBWWBBBK",
            "KBBBWPBBBBWPBBBK",
            "KBBBBBBBBBBBBBBK",
            "KBBBKDDDDDDKBBBK",
            "KBBBKDLBBLDKBBBK",
            "KDBBBKDDDDKBBBDK",
            "KDDBBBBBBBBBBDDK",
            "KKDDDDDDDDDDDDKK",
            ".K.KDBBBBBBDK.K.",
            "....KDDDDDDK....",
            "......KGGK......",
        ],
        'up': [
            "..KGK.KKKK.KGK..",
            "..KGKKBBBBKKGK..",
            ".KGKBBBBBBBBKGK.",
            ".KGKBBBBBBBBKGK.",
            "KKKBBBLBBBBBBKKK",
            "KBBBBDBBBBDBBBBK",
            "KBBBDBBBBBBDBBBK",
            "KBBBBBBBBBBBBBBK",
            "KBBBBBDDDDBBBBBK",
            "KBBBBDBBBBDBBBBK",
            "KDBBBBBBBBBBBBDK",
            "KDDBBBBBBBBBBDDK",
            "KKDDDDDDDDDDDDKK",
            ".K.KDBBBBBBDK.K.",
            "....KDDDDDDK....",
            "......KGGK......",
        ],
        'side': [
            "..KGK.KKKK.KGK..",
            "..KGKKBBBBKKGK..",
            ".KGKBBBBBBBBKGK.",
            ".KGKBBBBBBBBKGK.",
            "KKKBBBLBBBBBBKKK",
            "KBBBBBBBBBBWWBBK",
            "KBBBBBBBBBBWPBKK",
            "KBBBBBBBBBBBBBKG",
            "KBBBKDDDDDDKBBBK",
            "KBBBKDLBBLDKBBBK",
            "KDBBBKDDDDKBBBDK",
            "KDDBBBBBBBBBBDDK",
            "KKDDDDDDDDDDDDKK",
            ".K.KDBBBBBBDK.K.",
            "....KDDDDDDK....",
            "......KGGK......",
        ],
    }),

    # ---- ELECTRIC / EPIC : caged lightning orb ----
    ('sparkmote', 'sparkmote', {
        'down': [
            "......KYK.......",
            ".....KYAYK......",
            "....KKAAAKK.....",
            "...KAAAAAAAK....",
            "..KAALAAAAAAK...",
            "..KAWWAAAAWWK...",
            "..KAWPAAAAWPK...",
            "..KAAAAAAAAAK...",
            "..KVAAAYAAAVK...",
            "...KVAAYAAVK....",
            "....KVVVVVK.....",
            ".....KYK.KYK....",
            "......K...K.....",
        ],
        'up': [
            "......KYK.......",
            ".....KYAYK......",
            "....KKAAAKK.....",
            "...KAAAAAAAK....",
            "..KAALAAAAAAK...",
            "..KAAVAAVAAAK...",
            "..KAVAAAAVAAK...",
            "..KAAAAAAAAAK...",
            "..KVAAAYAAAVK...",
            "...KVAAYAAVK....",
            "....KVVVVVK.....",
            ".....KYK.KYK....",
            "......K...K.....",
        ],
        'side': [
            "......KYK.......",
            ".....KYAYK......",
            "....KKAAAKK.....",
            "...KAAAAAAAK....",
            "..KAALAAAAAAK...",
            "..KAAAAAAAWWK...",
            "..KAAAAAAAWPKK..",
            "..KAAAAAAAAAKYK.",
            "..KVAAAYAAAVK...",
            "...KVAAYAAVK....",
            "....KVVVVVK.....",
            ".....KYK.KYK....",
            "......K...K.....",
        ],
    }),
    ('arcnode_mid', 'arcnode', {
        'down': [
            "..KYK..KYK..KYK.",
            "..KAKKKAAKKKAK..",
            ".KAAAAAAAAAAAK..",
            ".KAALAAAAAAAAK..",
            "KAAAAAAAAAAAAAK.",
            "KAAWWAAAAAWWAAK.",
            "KAAWPAAAAAWPAAK.",
            "KAAAAAAAAAAAAAK.",
            "KAAAKYYAYYKAAAK.",
            "KVAAAKYAYKAAAVK.",
            ".KVVAAAAAAAVVK..",
            ".KKVVVVVVVVVKK..",
            "..KYK.....KYK...",
            "..K.........K...",
        ],
        'up': [
            "..KYK..KYK..KYK.",
            "..KAKKKAAKKKAK..",
            ".KAAAAAAAAAAAK..",
            ".KAALAAAAAAAAK..",
            "KAAAAAVVVAAAAAK.",
            "KAAAAVAAAVAAAAK.",
            "KAAAVAAAAAVAAAK.",
            "KAAAAVAAAVAAAAK.",
            "KAAAAAVVVAAAAAK.",
            "KVAAAAAAAAAAAVK.",
            ".KVVAAAAAAAVVK..",
            ".KKVVVVVVVVVKK..",
            "..KYK.....KYK...",
            "..K.........K...",
        ],
        'side': [
            "..KYK..KYK..KYK.",
            "..KAKKKAAKKKAK..",
            ".KAAAAAAAAAAAK..",
            ".KAALAAAAAAAAK..",
            "KAAAAAAAAAAAAAK.",
            "KAAAAAAAAAWWAAK.",
            "KAAAAAAAAAWPAKKK",
            "KAAAAAAAAAAAAKYK",
            "KAAAKYYAYYKAAAK.",
            "KVAAAKYAYKAAAVK.",
            ".KVVAAAAAAAVVK..",
            ".KKVVVVVVVVVKK..",
            "..KYK.....KYK...",
            "..K.........K...",
        ],
    }),
    ('tesladon_evo', 'tesladon', {
        'down': [
            "KYK.KYK.KYK.KYK.",
            "KAKKKAKKKAKKKAK.",
            "KAAAAAAAAAAAAAAK",
            "KAALAAAAAAAAAAAK",
            "KAAAAAAAAAAAAAAK",
            "KAWWAAAAAAAAWWAK",
            "KAWPAAAAAAAAWPAK",
            "KAAAAAAAAAAAAAAK",
            "KAAKYYAYYAYYKAAK",
            "KAAKYAAYAAYAKAAK",
            "KAAKYYAYYAYYKAAK",
            "KVAAAKKKKKKAAAVK",
            "KVVAAAAAAAAAAVVK",
            "KKVVVVVVVVVVVVKK",
            "KYK.KYK.KYK.KYK.",
            "K.....K.....K...",
        ],
        'up': [
            "KYK.KYK.KYK.KYK.",
            "KAKKKAKKKAKKKAK.",
            "KAAAAAAAAAAAAAAK",
            "KAALAAAAAAAAAAAK",
            "KAAAAAVVVVAAAAAK",
            "KAAAAVAAAAVAAAAK",
            "KAAAVAAAAAAVAAAK",
            "KAAVAAAAAAAAVAAK",
            "KAAAVAAAAAAVAAAK",
            "KAAAAVAAAAVAAAAK",
            "KAAAAAVVVVAAAAAK",
            "KVAAAAAAAAAAAAVK",
            "KVVAAAAAAAAAAVVK",
            "KKVVVVVVVVVVVVKK",
            "KYK.KYK.KYK.KYK.",
            "K.....K.....K...",
        ],
        'side': [
            "KYK.KYK.KYK.KYK.",
            "KAKKKAKKKAKKKAK.",
            "KAAAAAAAAAAAAAAK",
            "KAALAAAAAAAAAAAK",
            "KAAAAAAAAAAAAAAK",
            "KAAAAAAAAAAAWWAK",
            "KAAAAAAAAAAAWPAK",
            "KAAAAAAAAAAAAAKK",
            "KAAKYYAYYAYYKAKY",
            "KAAKYAAYAAYAKAAK",
            "KAAKYYAYYAYYKAAK",
            "KVAAAKKKKKKAAAVK",
            "KVVAAAAAAAAAAVVK",
            "KKVVVVVVVVVVVVKK",
            "KYK.KYK.KYK.KYK.",
            "K.....K.....K...",
        ],
    }),
]
