# Third batch of hand-authored tower monsters - see custom_tower_art.py for
# the full style notes and the grid/palette format (reused verbatim here,
# same as custom_tower_art2.py).
#
# Batches one and two each filled empty or thin cells of the type/rarity
# gacha table; by the time this batch was written every cell already had at
# least one catchable species, so this batch instead rounds out the
# thinnest remaining cell of each type (one more per type: FIRE/COMMON,
# WATER/COMMON, GRASS/RARE, ELECTRIC/COMMON, EARTH/RARE, NORMAL/EPIC) so
# every type has real pull variety at more than one rarity, not just a
# bigger total count.
#
# New silhouettes, not reskins of the ones already on the sheet: a legless
# coiled salamander (no other line drops the shared stub-leg base), a
# teardrop tadpole tapering to a single tail-fin, a flower-sprite ringed by
# a petal crown, a round-eared mouse with a zigzag lightning tail, a
# square-jawed rock pup with floppy stone ears, and a legless ghost with a
# wavy hem instead of feet. Same conventions as every other line: compact
# body in a clear margin, oversized 2px eyes with the pupil directly
# beneath, flat 2-3 tone fills with the darker shade low, 1px near-black
# outline, and each stage visibly larger/more ornamented than the last.

from custom_tower_art import K, W, P, PALETTES

PALETTES3 = {
    # FIRE/COMMON - coiled ember salamander
    'emberadder': {'K': K, 'W': W, 'P': P,
                   'R': (196, 70, 40, 255), 'M': (110, 34, 26, 255),
                   'F': (255, 214, 90, 255)},
    'cinderviper': {'K': K, 'W': W, 'P': P,
                    'R': (208, 64, 36, 255), 'M': (120, 32, 24, 255),
                    'F': (255, 220, 96, 255)},
    'infernasp': {'K': K, 'W': W, 'P': P,
                  'R': (222, 58, 32, 255), 'M': (128, 28, 22, 255),
                  'F': (255, 228, 108, 255), 'O': (255, 150, 48, 255)},

    # WATER/COMMON - teardrop tadpole
    'tadpip': {'K': K, 'W': W, 'P': P,
               'U': (108, 186, 214, 255), 'V': (54, 126, 168, 255),
               'L': (198, 232, 244, 255)},
    'ripplefin': {'K': K, 'W': W, 'P': P,
                  'U': (98, 178, 210, 255), 'V': (46, 116, 160, 255),
                  'L': (196, 232, 246, 255)},
    'tsunarine': {'K': K, 'W': W, 'P': P,
                  'U': (88, 168, 204, 255), 'V': (38, 106, 152, 255),
                  'L': (206, 238, 250, 255), 'F': (150, 216, 236, 255)},

    # GRASS/RARE - flower sprite with a petal crown
    'petaline': {'K': K, 'W': W, 'P': P,
                 'G': (100, 176, 90, 255), 'E': (48, 104, 54, 255),
                 'B': (232, 132, 168, 255), 'Y': (250, 216, 92, 255)},
    'petalguard': {'K': K, 'W': W, 'P': P,
                   'G': (94, 170, 84, 255), 'E': (44, 98, 50, 255),
                   'B': (222, 116, 156, 255), 'Y': (250, 216, 92, 255)},
    'bloomqueen': {'K': K, 'W': W, 'P': P,
                   'G': (86, 162, 78, 255), 'E': (40, 92, 46, 255),
                   'B': (212, 100, 146, 255), 'Y': (252, 220, 100, 255)},

    # ELECTRIC/COMMON - round-eared mouse with a bolt tail
    'voltmouse': {'K': K, 'W': W, 'P': P,
                  'Y': (240, 216, 96, 255), 'D': (186, 152, 44, 255),
                  'B': (128, 208, 244, 255)},
    'amperat': {'K': K, 'W': W, 'P': P,
                'Y': (244, 220, 100, 255), 'D': (180, 146, 40, 255),
                'B': (118, 200, 240, 255)},
    'galvatail': {'K': K, 'W': W, 'P': P,
                  'Y': (248, 224, 106, 255), 'D': (172, 138, 36, 255),
                  'B': (108, 192, 236, 255), 'F': (255, 250, 200, 255)},

    # EARTH/RARE - square-jawed rock pup, floppy stone ears
    'stonepup': {'K': K, 'W': W, 'P': P,
                 'S': (150, 138, 120, 255), 'D': (92, 84, 70, 255),
                 'E': (112, 102, 88, 255)},
    'boulderhound': {'K': K, 'W': W, 'P': P,
                      'S': (144, 132, 114, 255), 'D': (86, 78, 64, 255),
                      'E': (108, 98, 84, 255)},
    'granitewolf': {'K': K, 'W': W, 'P': P,
                    'S': (138, 126, 108, 255), 'D': (80, 72, 58, 255),
                    'E': (104, 94, 80, 255), 'L': (196, 184, 164, 255)},

    # NORMAL/EPIC - legless ghost, wavy hem instead of feet
    'wisplet': {'K': K, 'W': W, 'P': P,
                'C': (222, 220, 236, 255), 'D': (156, 152, 178, 255),
                'L': (200, 232, 255, 255)},
    'phantorb': {'K': K, 'W': W, 'P': P,
                 'C': (216, 214, 234, 255), 'D': (146, 142, 170, 255),
                 'L': (196, 228, 255, 255)},
    'spectralord': {'K': K, 'W': W, 'P': P,
                    'C': (210, 208, 232, 255), 'D': (138, 134, 164, 255),
                    'L': (192, 224, 255, 255), 'Y': (250, 240, 190, 255)},
}

# render_monster (custom_tower_art.py) looks palettes up in the module-level
# PALETTES dict by key - merge this batch's in so it resolves regardless of
# import order.
PALETTES.update(PALETTES3)

CUSTOM_MONSTERS3 = [
    # ---- FIRE / COMMON : coiled ember salamander ----
    ('emberadder', 'emberadder', {
        'down': [
            ".......KK.......",
            "......KFFK......",
            ".....KKFFKK.....",
            "....KRRRRRRK....",
            "...KRRRRRRRRK...",
            "..KRRWWRRWWRRK..",
            "..KRRWPRRWPRRK..",
            "..KRRRRRRRRRRK..",
            "..KRRRKMMKRRRK..",
            "...KRRRRRRRRK...",
            "....KRRRRRRK....",
            ".....KFRRFK.....",
            "......KFFK......",
            ".......KK.......",
        ],
        'up': [
            ".......KK.......",
            "......KFFK......",
            ".....KKFFKK.....",
            "....KRRRRRRK....",
            "...KRRRRRRRRK...",
            "..KRRRMRRMRRK...",
            "..KRRRRMMRRRK...",
            "..KRRRRRRRRRRK..",
            "..KRRRKMMKRRRK..",
            "...KRRRRRRRRK...",
            "....KRRRRRRK....",
            ".....KFRRFK.....",
            "......KFFK......",
            ".......KK.......",
        ],
        'side': [
            ".......KK.......",
            "......KFFK......",
            ".....KKFFKK.....",
            "....KRRRRRRK....",
            "...KRRRRRRRRK...",
            "..KRRRRRRRWWK...",
            "..KRRRRRRRWPKKK.",
            "..KRRRRRRRRRKFK.",
            "..KRRRKMMKRRRK..",
            "...KRRRRRRRRK...",
            "....KRRRRRRK....",
            ".....KFRRFK.....",
            "......KFFK......",
            ".......KK.......",
        ],
    }),
    ('cinderviper_mid', 'cinderviper', {
        'down': [
            "...K.......K....",
            "..KFK.....KFK...",
            ".KKFFK...KFFKK..",
            ".KRRRRK.KRRRRK..",
            "KRRRRRRKRRRRRRK.",
            "KRRWWRRRRRWWRRK.",
            "KRRWPRRRRRWPRRK.",
            "KRRRRRRRRRRRRRK.",
            "KRRRRKMMKRRRRRK.",
            ".KRRRRRRRRRRRK..",
            ".KRRRRRRRRRRK...",
            "..KRRRRRRRRK....",
            "...KFRRRRFK.....",
            "....KFRRFK......",
            ".....KFFK.......",
            "......KK........",
        ],
        'up': [
            "...K.......K....",
            "..KFK.....KFK...",
            ".KKFFK...KFFKK..",
            ".KRRRRK.KRRRRK..",
            "KRRRRRRKRRRRRRK.",
            "KRRRMRRRRRMRRRK.",
            "KRRRRMRRMRRRRK..",
            "KRRRRRRRRRRRRRK.",
            "KRRRRKMMKRRRRRK.",
            ".KRRRRRRRRRRRK..",
            ".KRRRRRRRRRRK...",
            "..KRRRRRRRRK....",
            "...KFRRRRFK.....",
            "....KFRRFK......",
            ".....KFFK.......",
            "......KK........",
        ],
        'side': [
            "...K.......K....",
            "..KFK.....KFK...",
            ".KKFFK...KFFKK..",
            ".KRRRRK.KRRRRK..",
            "KRRRRRRKRRRRRRK.",
            "KRRRRRRRRRRRWWK.",
            "KRRRRRRRRRRRWPKK",
            "KRRRRRRRRRRRRRKF",
            "KRRRRKMMKRRRRRK.",
            ".KRRRRRRRRRRRK..",
            ".KRRRRRRRRRRK...",
            "..KRRRRRRRRK....",
            "...KFRRRRFK.....",
            "....KFRRFK......",
            ".....KFFK.......",
            "......KK........",
        ],
    }),
    ('infernasp_evo', 'infernasp', {
        'down': [
            "..K.K.......K.K.",
            ".KFKFK.....KFKFK",
            "KKOFFK.....KFFOK",
            "KRRRRK.....KRRRR",
            "KRRRRRK...KRRRRR",
            "KRRRRRRK.KRRRRRR",
            ".KRRWWRRKRRWWRRK",
            ".KRRWPRRRRRWPRRK",
            ".KRRRRRRRRRRRRRK",
            ".KRRRRKMMKRRRRRK",
            "..KRRRRRRRRRRRK.",
            "..KRRRRRRRRRRK..",
            "...KRRRRRRRRK...",
            "....KORRRRROK...",
            ".....KFRRRFK....",
            "......KFFFK.....",
        ],
        'up': [
            "..K.K.......K.K.",
            ".KFKFK.....KFKFK",
            "KKOFFK.....KFFOK",
            "KRRRRK.....KRRRR",
            "KRRRRRK...KRRRRR",
            "KRRRRRRK.KRRRRRR",
            ".KRRRMRRRRRMRRK.",
            ".KRRRRMRRMRRRRK.",
            ".KRRRRRRRRRRRRRK",
            ".KRRRRKMMKRRRRRK",
            "..KRRRRRRRRRRRK.",
            "..KRRRRRRRRRRK..",
            "...KRRRRRRRRK...",
            "....KORRRRROK...",
            ".....KFRRRFK....",
            "......KFFFK.....",
        ],
        'side': [
            "..K.K.......K.K.",
            ".KFKFK.....KFKFK",
            "KKOFFK.....KFFOK",
            "KRRRRK.....KRRRR",
            "KRRRRRK...KRRRRR",
            "KRRRRRRK.KRRRRWW",
            "KRRRRRRRRRRRWPKK",
            "KRRRRRRRRRRRRRKF",
            "KRRRRRRRRRRRRRKO",
            ".KRRRRKMMKRRRRRK",
            "..KRRRRRRRRRRRK.",
            "..KRRRRRRRRRRK..",
            "...KRRRRRRRRK...",
            "....KORRRRROK...",
            ".....KFRRRFK....",
            "......KFFFK.....",
        ],
    }),
    # ---- WATER / COMMON : teardrop tadpole ----
    ('tadpip', 'tadpip', {
        'down': [
            "......KKKK......",
            ".....KUUUUK.....",
            "....KULUUUUK....",
            "....KUUUUUUK....",
            "....KWWUUWWK....",
            "....KWPUUWPK....",
            "....KUUUUUUK....",
            ".....KUUUUK.....",
            "......KVVK......",
            ".......KVK......",
            ".......KVK......",
            "........K.......",
        ],
        'up': [
            "......KKKK......",
            ".....KUUUUK.....",
            "....KULUUUUK....",
            "....KUUUUUUK....",
            "....KUUVVUUK....",
            "....KUVUUVUK....",
            "....KUUUUUUK....",
            ".....KUUUUK.....",
            "......KVVK......",
            ".......KVK......",
            ".......KVK......",
            "........K.......",
        ],
        'side': [
            "......KKKK......",
            ".....KUUUUK.....",
            "....KULUUUUK....",
            "....KUUUUUUK....",
            "....KUUUUWWK....",
            "....KUUUUWPKK...",
            "....KUUUUUUK....",
            ".....KUUUUK.....",
            "......KVVKV.....",
            ".......KVKVK....",
            "........KVK.....",
            ".........K......",
        ],
    }),
    ('ripplefin_mid', 'ripplefin', {
        'down': [
            ".....KKKKKK.....",
            "...KKUUUUUUKK...",
            "..KUULUUUUUUK...",
            "..KUUUUUUUUUK...",
            "..KUWWUUUUWWK...",
            "..KUWPUUUUWPK...",
            "..KUUUUUUUUUK...",
            "...KUUUUUUUK....",
            "....KVUUUUVK....",
            ".....KVVVVK.....",
            "....KV.KK.VK....",
            "....KV..K..VK...",
            ".....K.......K..",
        ],
        'up': [
            ".....KKKKKK.....",
            "...KKUUUUUUKK...",
            "..KUULUUUUUUK...",
            "..KUUUUUUUUUK...",
            "..KUUUVVVUUUK...",
            "..KUUVUUUVUUK...",
            "..KUUUUUUUUUK...",
            "...KUUUUUUUK....",
            "....KVUUUUVK....",
            ".....KVVVVK.....",
            "....KV.KK.VK....",
            "....KV..K..VK...",
            ".....K.......K..",
        ],
        'side': [
            ".....KKKKKK.....",
            "...KKUUUUUUKK...",
            "..KUULUUUUUUK...",
            "..KUUUUUUUUUK...",
            "..KUUUUUUUWWK...",
            "..KUUUUUUUWPKK..",
            "..KUUUUUUUUUK...",
            "...KUUUUUUUK....",
            "....KVUUUUVKV...",
            ".....KVVVVKVK...",
            "....KV.KKVK.....",
            "....KV..KVK.....",
            ".....K..K.......",
        ],
    }),
    ('tsunarine_evo', 'tsunarine', {
        'down': [
            "...KKKKKKKKK....",
            "..KUUUUUUUUUK...",
            ".KUUULUUUUULUK..",
            ".KUUUUUUUUUUUK..",
            "KUWWUUUUUUUWWUK.",
            "KUWPUUUUUUUWPUK.",
            "KUUUUUUUUUUUUUK.",
            ".KUUFUUUUUFUUK..",
            ".KUUUUUUUUUUUK..",
            "..KVUUUUUUUVK...",
            "...KVVUUUUVVK...",
            "...KV.KVVK.VK...",
            "..KV..K..K..VK..",
            "..KV.........K..",
        ],
        'up': [
            "...KKKKKKKKK....",
            "..KUUUUUUUUUK...",
            ".KUUULUUUUULUK..",
            ".KUUUUUUUUUUUK..",
            "KUUUUVVVVVUUUK..",
            "KUUUVUUUUUVUUK..",
            "KUUUUUUUUUUUUUK.",
            ".KUUFUUUUUFUUK..",
            ".KUUUUUUUUUUUK..",
            "..KVUUUUUUUVK...",
            "...KVVUUUUVVK...",
            "...KV.KVVK.VK...",
            "..KV..K..K..VK..",
            "..KV.........K..",
        ],
        'side': [
            "...KKKKKKKKK....",
            "..KUUUUUUUUUK...",
            ".KUUULUUUUULUK..",
            ".KUUUUUUUUUUUK..",
            "KUUUUUUUUUUWWK..",
            "KUUUUUUUUUUWPKK.",
            "KUUUUUUUUUUUUKF.",
            ".KUUFUUUUUFUUK..",
            ".KUUUUUUUUUUUK..",
            "..KVUUUUUUUVKV..",
            "...KVVUUUUVVKVK.",
            "...KV.KVVKVK....",
            "..KV..K..KVK....",
            "..KV......K.....",
        ],
    }),
    # ---- GRASS / RARE : flower sprite with a petal crown ----
    ('petaline', 'petaline', {
        'down': [
            "....B.......B...",
            "...BYB.....BYB..",
            "..B..B.....B..B.",
            "....KKKKKKKK....",
            "...KGGGGGGGGK...",
            "..KGGGGGGGGGGK..",
            "..KGWWGGGGWWGK..",
            "..KGWPGGGGWPGK..",
            "..KGGGGGGGGGGK..",
            "..KGGGKEEKGGGK..",
            "...KEGGGGGGEK...",
            "....KEEEEEEK....",
            ".....KE..EK.....",
        ],
        'up': [
            "....B.......B...",
            "...BYB.....BYB..",
            "..B..B.....B..B.",
            "....KKKKKKKK....",
            "...KGGGGGGGGK...",
            "..KGGGGGGGGGGK..",
            "..KGGGEEGGGGK...",
            "..KGGEEEEGGGK...",
            "..KGGGGGGGGGGK..",
            "..KGGGKEEKGGGK..",
            "...KEGGGGGGEK...",
            "....KEEEEEEK....",
            ".....KE..EK.....",
        ],
        'side': [
            "....B.......B...",
            "...BYB.....BYB..",
            "..B..B.....B..B.",
            "....KKKKKKKK....",
            "...KGGGGGGGGK...",
            "..KGGGGGGGGGGK..",
            "..KGGGGGGGWWGK..",
            "..KGGGGGGGWPGKK.",
            "..KGGGGGGGGGGKBK",
            "..KGGGKEEKGGGK..",
            "...KEGGGGGGEK...",
            "....KEEEEEEK....",
            ".....KE..EK.....",
        ],
    }),
    ('petalguard_mid', 'petalguard', {
        'down': [
            "..B...B..B...B..",
            ".BYB.BYB.BYB.BYB",
            "..B...B..B...B..",
            ".....KKKKKKK....",
            "....KGGGGGGGK...",
            "...KGGGGGGGGGK..",
            "..KGGWWGGGGWWGK.",
            "..KGGWPGGGGWPGK.",
            "..KGGGGGGGGGGGK.",
            "..KGGGGKEEKGGGK.",
            "..KGGGGGGGGGGGK.",
            "...KEGGGGGGGEK..",
            "....KEEEEEEEEK..",
            ".....KE.KK.EK...",
        ],
        'up': [
            "..B...B..B...B..",
            ".BYB.BYB.BYB.BYB",
            "..B...B..B...B..",
            ".....KKKKKKK....",
            "....KGGGGGGGK...",
            "...KGGGGGGGGGK..",
            "..KGGGEEEEGGGK..",
            "..KGGEEEEEEGGK..",
            "..KGGGGGGGGGGGK.",
            "..KGGGGKEEKGGGK.",
            "..KGGGGGGGGGGGK.",
            "...KEGGGGGGGEK..",
            "....KEEEEEEEEK..",
            ".....KE.KK.EK...",
        ],
        'side': [
            "..B...B..B...B..",
            ".BYB.BYB.BYB.BYB",
            "..B...B..B...B..",
            ".....KKKKKKK....",
            "....KGGGGGGGK...",
            "...KGGGGGGGGGK..",
            "..KGGGGGGGGWWGK.",
            "..KGGGGGGGGWPGKK",
            "..KGGGGGGGGGGGKB",
            "..KGGGGKEEKGGGK.",
            "..KGGGGGGGGGGGK.",
            "...KEGGGGGGGEK..",
            "....KEEEEEEEEK..",
            ".....KE.KK.EK...",
        ],
    }),
    ('bloomqueen_evo', 'bloomqueen', {
        'down': [
            "B..B...B...B..B.",
            "BYBBYB.BYBBYB...",
            ".B.B.B.B.B.B....",
            "......KKKKKK....",
            ".....KGGGGGGK...",
            "....KGGGGGGGGK..",
            "...KGGGGGGGGGGK.",
            "..KGGWWGGGGWWGK.",
            "..KGGWPGGGGWPGK.",
            "..KGGGGGGGGGGGK.",
            "..KGGGGKYYKGGGK.",
            "..KGGGGGGGGGGGK.",
            "...KEGGGGGGGEK..",
            "....KEEEEEEEEK..",
            ".....KEE.KEEK...",
            "......K...K.....",
        ],
        'up': [
            "B..B...B...B..B.",
            "BYBBYB.BYBBYB...",
            ".B.B.B.B.B.B....",
            "......KKKKKK....",
            ".....KGGGGGGK...",
            "....KGGGGGGGGK..",
            "...KGGGGGGGGGGK.",
            "..KGGGEEEEEGGK..",
            "..KGGEEEEEEEGK..",
            "..KGGGGGGGGGGGK.",
            "..KGGGGKYYKGGGK.",
            "..KGGGGGGGGGGGK.",
            "...KEGGGGGGGEK..",
            "....KEEEEEEEEK..",
            ".....KEE.KEEK...",
            "......K...K.....",
        ],
        'side': [
            "B..B...B...B..B.",
            "BYBBYB.BYBBYB...",
            ".B.B.B.B.B.B....",
            "......KKKKKK....",
            ".....KGGGGGGK...",
            "....KGGGGGGGGK..",
            "...KGGGGGGGGGGK.",
            "..KGGGGGGGGGWWK.",
            "..KGGGGGGGGGWPKK",
            "..KGGGGGGGGGGGKB",
            "..KGGGGKYYKGGGK.",
            "..KGGGGGGGGGGGK.",
            "...KEGGGGGGGEK..",
            "....KEEEEEEEEK..",
            ".....KEE.KEEK...",
            "......K...K.....",
        ],
    }),
    # ---- ELECTRIC / COMMON : round-eared mouse, zigzag bolt tail ----
    ('voltmouse', 'voltmouse', {
        'down': [
            "....KK....KK....",
            "...KYYK..KYYK...",
            "..KYYYYKKYYYYK..",
            "..KYYYYYYYYYYK..",
            "..KYWWYYYYWWYK..",
            "..KYWPYYYYWPYK..",
            "..KYYYYYYYYYYK..",
            "..KYYYKDDKYYYK..",
            "...KDYYYYYYDK...",
            "....KDDDDDDK....",
            ".....KK..KK.....",
        ],
        'up': [
            "....KK....KK....",
            "...KYYK..KYYK...",
            "..KYYYYKKYYYYK..",
            "..KYYYYYYYYYYK..",
            "..KYYYDDYYYYK...",
            "..KYYDDDDYYYK...",
            "..KYYYYYYYYYYK..",
            "..KYYYKDDKYYYK..",
            "...KDYYYYYYDK...",
            "....KDDDDDDK....",
            ".....KK..KK.....",
        ],
        'side': [
            "....KK....KK....",
            "...KYYK..KYYK...",
            "..KYYYYKKYYYYK..",
            "..KYYYYYYYYYYK..",
            "..KYYYYYYYWWK...",
            "..KYYYYYYYWPKK..",
            "..KYYYYYYYYYYK..",
            "..KYYYKDDKYYYK..",
            "...KDYYYYYYDK...",
            "....KDDDDDDKB...",
            ".....KK..KKBKB..",
        ],
    }),
    ('amperat_mid', 'amperat', {
        'down': [
            "...KKK....KKK...",
            "..KYYYK..KYYYK..",
            ".KYYYYYKKYYYYYK.",
            ".KYYYYYYYYYYYYK.",
            "KYYWWYYYYYWWYYK.",
            "KYYWPYYYYYWPYYK.",
            "KYYYYYYYYYYYYYK.",
            "KYYYYKDDKYYYYYK.",
            ".KYYYYYYYYYYYK..",
            "..KDYYYYYYYDK...",
            "...KDDDDDDDK....",
            "....KK....KK....",
        ],
        'up': [
            "...KKK....KKK...",
            "..KYYYK..KYYYK..",
            ".KYYYYYKKYYYYYK.",
            ".KYYYYYYYYYYYYK.",
            "KYYYYDDYYYYYYYK.",
            "KYYYDDDDYYYYYYK.",
            "KYYYYYYYYYYYYYK.",
            "KYYYYKDDKYYYYYK.",
            ".KYYYYYYYYYYYK..",
            "..KDYYYYYYYDK...",
            "...KDDDDDDDK....",
            "....KK....KK....",
        ],
        'side': [
            "...KKK....KKK...",
            "..KYYYK..KYYYK..",
            ".KYYYYYKKYYYYYK.",
            ".KYYYYYYYYYYYYK.",
            "KYYYYYYYYYYYWWK.",
            "KYYYYYYYYYYYWPKK",
            "KYYYYYYYYYYYYYKB",
            "KYYYYKDDKYYYYYKB",
            ".KYYYYYYYYYYYKB.",
            "..KDYYYYYYYDK...",
            "...KDDDDDDDK....",
            "....KK....KK....",
        ],
    }),
    ('galvatail_evo', 'galvatail', {
        'down': [
            "..KKK....KKK....",
            ".KYFYK..KYFYK...",
            "KYYYYYKKYYYYYK..",
            "KYYYYYYYYYYYYYK.",
            "KYWWYYYYYYWWYYK.",
            "KYWPYYYYYYWPYYK.",
            "KYYYYYYYYYYYYYK.",
            "KYYYYYKDDKYYYYK.",
            "KYYYYYYYYYYYYYK.",
            ".KYYYYYYYYYYYK..",
            "..KDYYYYYYYDK...",
            "...KDDDDDDDDK...",
            "....KK.....KK...",
        ],
        'up': [
            "..KKK....KKK....",
            ".KYFYK..KYFYK...",
            "KYYYYYKKYYYYYK..",
            "KYYYYYYYYYYYYYK.",
            "KYYYYDDDDYYYYYK.",
            "KYYYDDDDDDYYYYK.",
            "KYYYYYYYYYYYYYK.",
            "KYYYYYKDDKYYYYK.",
            "KYYYYYYYYYYYYYK.",
            ".KYYYYYYYYYYYK..",
            "..KDYYYYYYYDK...",
            "...KDDDDDDDDK...",
            "....KK.....KK...",
        ],
        'side': [
            "..KKK....KKK....",
            ".KYFYK..KYFYK...",
            "KYYYYYKKYYYYYK..",
            "KYYYYYYYYYYYYYK.",
            "KYYYYYYYYYYYYWWK",
            "KYYYYYYYYYYYYWPK",
            "KYYYYYYYYYYYYYKB",
            "KYYYYYKDDKYYYYKB",
            "KYYYYYYYYYYYYYKB",
            ".KYYYYYYYYYYYK..",
            "..KDYYYYYYYDK...",
            "...KDDDDDDDDK...",
            "....KK.....KK...",
        ],
    }),
    # ---- EARTH / RARE : square-jawed rock pup, floppy stone ears ----
    ('stonepup', 'stonepup', {
        'down': [
            ".KEK........KEK.",
            ".KEEK......KEEK.",
            "..KEEK....KEEK..",
            "..KEEKKKKKKEEK..",
            "..KSSSSSSSSSSK..",
            ".KSSSSSSSSSSSSK.",
            ".KSWWSSSSSWWSSK.",
            ".KSWPSSSSSWPSSK.",
            ".KSSSSSSSSSSSSK.",
            ".KSSSSKDDKSSSSK.",
            "..KDSSSSSSSSDK..",
            "...KDDDDDDDDK...",
            "....KK....KK....",
        ],
        'up': [
            ".KEK........KEK.",
            ".KEEK......KEEK.",
            "..KEEK....KEEK..",
            "..KEEKKKKKKEEK..",
            "..KSSSSSSSSSSK..",
            ".KSSSSSSSSSSSSK.",
            ".KSSSDSSSDSSSSK.",
            ".KSSDSSSSSDSSSK.",
            ".KSSSSSSSSSSSSK.",
            ".KSSSSKDDKSSSSK.",
            "..KDSSSSSSSSDK..",
            "...KDDDDDDDDK...",
            "....KK....KK....",
        ],
        'side': [
            ".KEK........KEK.",
            ".KEEK......KEEK.",
            "..KEEK....KEEK..",
            "..KEEKKKKKKEEK..",
            "..KSSSSSSSSSSK..",
            ".KSSSSSSSSSSSSK.",
            ".KSSSSSSSSSWWSK.",
            ".KSSSSSSSSSWPSKK",
            ".KSSSSSSSSSSSSK.",
            ".KSSSSKDDKSSSSK.",
            "..KDSSSSSSSSDK..",
            "...KDDDDDDDDK...",
            "....KK....KK....",
        ],
    }),
    ('boulderhound_mid', 'boulderhound', {
        'down': [
            "KEEK........KEEK",
            ".KEEK.......KEEK",
            "..KEEK.....KEEK.",
            "..KEEKKKKKKKEEK.",
            "..KSSSSSSSSSSSK.",
            ".KSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSWWSSSSSSWWSSK",
            "KSSWPSSSSSSWPSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSKDDDKSSSSK",
            ".KDSSSSSSSSSSDK.",
            "..KDDSSSSSSSSDDK",
            "...KDDDDDDDDDDK.",
            "....KK......KK..",
        ],
        'up': [
            "KEEK........KEEK",
            ".KEEK.......KEEK",
            "..KEEK.....KEEK.",
            "..KEEKKKKKKKEEK.",
            "..KSSSSSSSSSSSK.",
            ".KSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSDSSSSSDSSSSK",
            "KSSDSSSSSSSDSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSKDDDKSSSSK",
            ".KDSSSSSSSSSSDK.",
            "..KDDSSSSSSSSDDK",
            "...KDDDDDDDDDDK.",
            "....KK......KK..",
        ],
        'side': [
            "KEEK........KEEK",
            ".KEEK.......KEEK",
            "..KEEK.....KEEK.",
            "..KEEKKKKKKKEEK.",
            "..KSSSSSSSSSSSK.",
            ".KSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSWWK",
            "KSSSSSSSSSSSSWPK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSKDDDKSSSSK",
            ".KDSSSSSSSSSSDK.",
            "..KDDSSSSSSSSDDK",
            "...KDDDDDDDDDDK.",
            "....KK......KK..",
        ],
    }),
    ('granitewolf_evo', 'granitewolf', {
        'down': [
            "KEEEK......KEEEK",
            ".KEEEK.....KEEEK",
            "..KEEK.....KEEK.",
            "..KEEKKKKKKKEEK.",
            ".KLKSSSSSSSSKLK.",
            ".KSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSWWSSSSSSSWWSK",
            "KSSWPSSSSSSSWPSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSKDDDKSSSK",
            "KSSSSSSSSSSSSSSK",
            ".KDSSSSSSSSSSDK.",
            "..KDDSSSSSSSDDK.",
            "...KDDDDDDDDDK..",
            "....KK.......KK.",
        ],
        'up': [
            "KEEEK......KEEEK",
            ".KEEEK.....KEEEK",
            "..KEEK.....KEEK.",
            "..KEEKKKKKKKEEK.",
            ".KLKSSSSSSSSKLK.",
            ".KSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSDSSSSSSDSSSK",
            "KSSDSSSSSSSSDSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSKDDDKSSSK",
            "KSSSSSSSSSSSSSSK",
            ".KDSSSSSSSSSSDK.",
            "..KDDSSSSSSSDDK.",
            "...KDDDDDDDDDK..",
            "....KK.......KK.",
        ],
        'side': [
            "KEEEK......KEEEK",
            ".KEEEK.....KEEEK",
            "..KEEK.....KEEK.",
            "..KEEKKKKKKKEEK.",
            ".KLKSSSSSSSSKLK.",
            ".KSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSSSSSSSWWK",
            "KSSSSSSSSSSSSWPK",
            "KSSSSSSSSSSSSSSK",
            "KSSSSSSKDDDKSSSK",
            "KSSSSSSSSSSSSSSK",
            ".KDSSSSSSSSSSDK.",
            "..KDDSSSSSSSDDK.",
            "...KDDDDDDDDDK..",
            "....KK.......KK.",
        ],
    }),
    # ---- NORMAL / EPIC : legless ghost, wavy hem ----
    ('wisplet', 'wisplet', {
        'down': [
            "......KKKK......",
            ".....KCCCCK.....",
            "....KCCCCCCK....",
            "...KCCCCCCCCK...",
            "..KCWWCCCCWWCK..",
            "..KCWPCCCCWPCK..",
            "..KCCCCCCCCCCK..",
            "..KCCCCCCCCCCK..",
            "...KCCCCCCCCK...",
            "...KDCDCDCDDK...",
            "....K.K.K.K.....",
        ],
        'up': [
            "......KKKK......",
            ".....KCCCCK.....",
            "....KCCCCCCK....",
            "...KCCCCCCCCK...",
            "..KCCCDDCCCCK...",
            "..KCCDDDDCCCK...",
            "..KCCCCCCCCCCK..",
            "..KCCCCCCCCCCK..",
            "...KCCCCCCCCK...",
            "...KDCDCDCDDK...",
            "....K.K.K.K.....",
        ],
        'side': [
            "......KKKK......",
            ".....KCCCCK.....",
            "....KCCCCCCK....",
            "...KCCCCCCCCK...",
            "..KCCCCCCCWWK...",
            "..KCCCCCCCWPKK..",
            "..KCCCCCCCCCCK..",
            "..KCCCCCCCCCCK..",
            "...KCCCCCCCCK...",
            "...KDCDCDCDDK...",
            "....K.K.K.K.....",
        ],
    }),
    ('phantorb_mid', 'phantorb', {
        'down': [
            "L....KKKKKK....L",
            "....KCCCCCK.....",
            "....KCCCCCCCK...",
            "...KCCCCCCCCCK..",
            "..KCCCCCCCCCCCK.",
            "..KCWWCCCCCWWCK.",
            "..KCWPCCCCCWPCK.",
            "..KCCCCCCCCCCCK.",
            "..KCCCCCCCCCCCK.",
            "...KCCCCCCCCCK..",
            "...KDCDCDCDCDK..",
            "....K.K.K.K.K...",
        ],
        'up': [
            "L....KKKKKK....L",
            "....KCCCCCK.....",
            "....KCCCCCCCK...",
            "...KCCCCCCCCCK..",
            "..KCCCCDDCCCCK..",
            "..KCCCDDDDCCCK..",
            "..KCCCCCCCCCCCK.",
            "..KCCCCCCCCCCCK.",
            "..KCCCCCCCCCCCK.",
            "...KCCCCCCCCCK..",
            "...KDCDCDCDCDK..",
            "....K.K.K.K.K...",
        ],
        'side': [
            "L....KKKKKK....L",
            "....KCCCCCK.....",
            "....KCCCCCCCK...",
            "...KCCCCCCCCCK..",
            "..KCCCCCCCCCWWK.",
            "..KCCCCCCCCCWPKK",
            "..KCCCCCCCCCCCK.",
            "..KCCCCCCCCCCCK.",
            "..KCCCCCCCCCCCK.",
            "...KCCCCCCCCCK..",
            "...KDCDCDCDCDK..",
            "....K.K.K.K.K...",
        ],
    }),
    ('spectralord_evo', 'spectralord', {
        'down': [
            "L.....KKKK.....L",
            "..L...KYYK...L..",
            "....KCCCCCK.....",
            "....KCCCCCCCK...",
            "...KCCCCCCCCCK..",
            "..KCCCCCCCCCCCK.",
            "..KCWWCCCCCWWCK.",
            "..KCWPCCCCCWPCK.",
            "..KCCCCCCCCCCCK.",
            "..KCCCCKDDKCCCK.",
            "..KCCCCCCCCCCCK.",
            "...KCCCCCCCCCK..",
            "...KDCDCDCDCDK..",
            "....K.K.K.K.K...",
        ],
        'up': [
            "L.....KKKK.....L",
            "..L...KYYK...L..",
            "....KCCCCCK.....",
            "....KCCCCCCCK...",
            "...KCCCCCCCCCK..",
            "..KCCCCDDCCCCK..",
            "..KCCCDDDDCCCK..",
            "..KCCCCCCCCCCCK.",
            "..KCCCCCCCCCCCK.",
            "..KCCCCKDDKCCCK.",
            "..KCCCCCCCCCCCK.",
            "...KCCCCCCCCCK..",
            "...KDCDCDCDCDK..",
            "....K.K.K.K.K...",
        ],
        'side': [
            "L.....KKKK.....L",
            "..L...KYYK...L..",
            "....KCCCCCK.....",
            "....KCCCCCCCK...",
            "...KCCCCCCCCCK..",
            "..KCCCCCCCCCWWK.",
            "..KCCCCCCCCCWPKK",
            "..KCCCCCCCCCCCK.",
            "..KCCCCCCCCCCCK.",
            "..KCCCCKDDKCCCK.",
            "..KCCCCCCCCCCCK.",
            "...KCCCCCCCCCK..",
            "...KDCDCDCDCDK..",
            "....K.K.K.K.K...",
        ],
    }),
]
